spring.application.name=ai-workflow-platform


spring.datasource.url=jdbc:postgresql://localhost:5432/ai_workflow_platform
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


jwt.secret=change-this-to-a-long-random-secret-key
jwt.expiration=3600000


# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=workflow-execution-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.LongDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.LongSerializer

spring.ai.openai.api-key=${OPENAI_API_KEY}